name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ขั้นตอนที่ 1: ดึงโค้ดจาก repository
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # ขั้นตอนที่ 2: แก้ไขปัญหา path และ permission
    - name: Setup environment
      run: |
        echo "Current working directory: $(pwd)"
        echo "Contents of /home/runner/work:"
        ls -la /home/runner/work
        sudo chown -R runner:runner /home/runner/work

    # ขั้นตอนที่ 3: ติดตั้ง Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    # ขั้นตอนที่ 4: ตรวจสอบและติดตั้ง dependencies
    - name: Install dependencies
      run: |
        echo "Current directory contents:"
        ls -la
        
        # แก้ไขคำสั่ง npm ที่พิมพ์ผิด (npn -> npm)
        if ! command -v npm &> /dev/null; then
          echo "npm not found! Checking path..."
          which npm || echo "npm not in PATH"
          exit 1
        fi

        # ตรวจสอบไฟล์ lock ทั้งหมด
        if [ -f package-lock.json ]; then
          echo "Found package-lock.json, running npm ci..."
          npm ci
        elif [ -f npm-shrinkwrap.json ]; then
          echo "Found npm-shrinkwrap.json, running npm ci..."
          npm ci
        elif [ -f yarn.lock ]; then
          echo "Found yarn.lock, running yarn install..."
          npm install -g yarn
          yarn install --frozen-lockfile
        else
          echo "No lock file found, running npm install..."
          npm install
        fi

    # ขั้นตอนที่ 5: Build และ Test
    - run: npm run build --if-present
    - run: npm test
