name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    # ขั้นตอนที่ 1: ดึงโค้ดจาก repository
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # ตรวจสอบให้ดึงประวัติทั้งหมด

    # ขั้นตอนที่ 2: ตรวจสอบไฟล์ (สำหรับ debugging)
    - name: Check repository files
      run: |
        echo "=== ไฟล์ในโฟลเดอร์ปัจจุบัน ==="
        ls -la
        echo "=== กำลังค้นหาไฟล์ lock ==="
        find . -name "package-lock.json" -o -name "yarn.lock" -o -name "npm-shrinkwrap.json"

    # ขั้นตอนที่ 3: ติดตั้ง Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # ขั้นตอนที่ 4: ติดตั้ง dependencies
    - name: Install dependencies
      run: |
        # ตรวจสอบและติดตั้งตามไฟล์ lock ที่มีอยู่
        if [ -f package-lock.json ]; then
          echo "พบ package-lock.json, กำลังใช้ npm ci..."
          npm ci
        elif [ -f yarn.lock ]; then
          echo "พบ yarn.lock, กำลังใช้ yarn install..."
          yarn install --frozen-lockfile
        else
          echo "ไม่พบไฟล์ lock, กำลังใช้ npm install..."
          npm install
        fi

    # ขั้นตอนที่ 5: Build และ Test
    - run: npm run build --if-present
    - run: npm test
