name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # ดึงประวัติ commit ทั้งหมดเพื่อให้แน่ใจว่าได้ไฟล์ล่าสุด

    - name: Debug - List files (optional)
      run: ls -la  # สำหรับตรวจสอบว่าไฟล์ถูก checkout มาแล้ว

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - run: npm run build --if-present
    - run: npm test
